### ISSUE TITLE
IB Designables are not rendered in Storyboard

### ISSUE THREAD

**Issue by javierHolvi** [k-o-d-e-n/QUIckControl#1]
IB Designables are not rendered in Storyboard. Error prompt:
![screen shot 2017-02-08 at 09 21 25](https://cloud.githubusercontent.com/assets/23310846/22728772/0208d96a-ede0-11e6-9f82-c55132e7d6c7.png)

**Comment by k-o-d-e-n** [comment]
Insert this in podfile for avoiding errors.
```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
```
Rendering will be fixed soon.
